# Generated by Django 3.2.20 on 2026-06-16 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0035_quiz_question_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTestCase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='yaksh.testcase')),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
            ],
            bases=('yaksh.testcase',),
        ),
    ]
