# Generated by Django 3.2.20 on 2026-06-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0036_uploadtestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_seb_required',
            field=models.BooleanField(default=False, verbose_name='Require Safe Exam Browser'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='seb_config_key',
            field=models.CharField(blank=True, help_text='The Config Key Hash generated by SEB Configuration Tool', max_length=255, null=True, verbose_name='SEB Config Key'),
        ),
    ]
