# Generated by Django 3.2.20 on 2026-06-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0037_auto_20260618_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='seb_config_file',
            field=models.FileField(blank=True, help_text='Upload the .seb file for automatic student launching', null=True, upload_to='seb_configs/', verbose_name='SEB Config File'),
        ),
    ]
